addEventToNumbersButtons();
addEventToClearButton();
addEventToDeleteButton();
addEventToEqualButton();
addEventToMinusButton();
addEventToOperatorsButtons();
addEventToDotButton();
addEventToKeyPressed();
window.addEventListener("keydown", maxSizeDisplayError);
window.addEventListener("click", maxSizeDisplayError);
scaleButton();
removeScaleButton();
addEventToRemoveFocusOnButtons();
